[package]
name = "codelta_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.13"
ic-cdk = "0.17.1"
ic-cdk-macros = "0.17.1"
ic-ledger-types = "0.14.0"
icrc-ledger-types = "0.1.10"
serde = "1.0"
serde_bytes = "0.11"
